# Generated by Django 3.2.20 on 2023-08-01 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=0, verbose_name='删除标记位')),
                ('code', models.CharField(max_length=64, verbose_name='code')),
                ('name', models.CharField(max_length=64, verbose_name='部门名称')),
                ('superior_department_id', models.IntegerField(blank=True, null=True, verbose_name='上级部门ID')),
                ('department_path', models.CharField(blank=True, max_length=128, null=True, verbose_name='部门路径编码')),
            ],
            options={
                'verbose_name': '部门',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=0, verbose_name='删除标记位')),
                ('user_uid', models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='user_uid')),
                ('username', models.CharField(max_length=64, verbose_name='用户名')),
                ('password', models.CharField(max_length=128, verbose_name='密码')),
                ('email', models.CharField(blank=True, max_length=64, null=True, verbose_name='邮箱')),
                ('tel', models.CharField(blank=True, max_length=128, null=True, verbose_name='电话')),
                ('sex', models.CharField(blank=True, choices=[('male', '男'), ('female', '女'), ('unknown', '未知')], max_length=16, null=True, verbose_name='性别')),
                ('user_locked', models.BooleanField(default=False, verbose_name='是否锁定')),
            ],
            options={
                'verbose_name': '用户表',
            },
        ),
        migrations.CreateModel(
            name='UserLeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=0, verbose_name='删除标记位')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_leader_leader', to='account.user', to_field='user_uid', verbose_name='领导')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_leader_user', to='account.user', to_field='user_uid', verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户领导',
            },
        ),
    ]
