# -*- coding: utf-8 -*-
# @Time    : 2023/8/8 12:30
# @Author  : wwz
# @File    : base.py
# @Software: PyCharm
"""
Django settings for xops project.

Generated by 'django-admin startproject' using Django 3.2.20.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-y7=)k4cnsx1o-0n=sj7-87dqv5@#wc%t4veclr!5n0c+-8jhba'
PUBLIC_KEY = "MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAN7/EKJ1O946bQU/UM0FjiIHUHUIWI81y5BduD5F0K4gYpQDdC/v29AK74PQEXTQExmj+P/IagmUeEjDZBuk9b0CAwEAAQ=="
PRIVATE_KEY = "MIIBVAIBADANBgkqhkiG9w0BAQEFAASCAT4wggE6AgEAAkEA3v8QonU73jptBT9QzQWOIgdQdQhYjzXLkF24PkXQriBilAN0L+/b0Arvg9ARdNATGaP4/8hqCZR4SMN\
               kG6T1vQIDAQABAkB539lNkNkZicEPvx0AEGsv+eNlMxyDmJka273YevukThVL0VLmRnVGHA9FVQIRErsTmwjxKSAYZsPcjTRC3YDBAiEA+8MEs3BRIvHW0GWc2ZudhE\
               MWX45KnIXQ/FtMhK65s3kCIQDiwBSPqgLmsSqbGTHr8bFKtUn/MKpZiFiS4AjBqfGfZQIgamcHq5bCk9RGB5mKauW78tQvtn76xaBArQchFcqKrXECIQDB81xi+h/bJ\
               WV1Htrln2lvppuxrPW4+XgRwZGb3XowRQIgRcsl/o6G3f9dDKPfnqpqkEomdAhRddsMCua4Bol0Uho="
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'account',
    'common'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'account.middlewares.LoginCheck',
]

ROOT_URLCONF = 'xops.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'shangan',
        'USER': 'root',
        'PASSWORD': 'aaaaaa',
        "HOST": "8.130.45.165",
        'PORT': '3306',
        'CHARSET': 'utf8',
        'OPTIONS': {'init_command': "SET sql_mode='STRICT_TRANS_TABLES'"}
    }
}

WSGI_APPLICATION = 'xops.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
